# Generated by Django 4.1.3 on 2023-01-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_if_verified_email_email_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_verified_email',
            new_name='is_verified_email',
        ),
    ]
