# Generated by Django 4.1.3 on 2023-01-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_bascet_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
